// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// Command: npx gltfjsx@6.2.13 javascript.glb -t -T
// Files: javascript.glb [53.95KB] > javascript-transformed.glb [6.45KB] (88%)
// */

// import * as THREE from 'three'
// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'
// import { GLTF } from 'three-stdlib'

// type GLTFResult = GLTF & {
//   nodes: {
//     Object_13: THREE.Mesh
//     Object_13_1: THREE.Mesh
//   }
//   materials: {
//     JAVASCRIPT: THREE.MeshStandardMaterial
//     BORDAS_CROMADO: THREE.MeshStandardMaterial
//   }
// }

// type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

// export function Model(props: JSX.IntrinsicElements['group']) {
//   const { nodes, materials } = useGLTF('/javascript-transformed.glb') as GLTFResult
//   return (
//     <group {...props} dispose={null}>
//       <group position={[-0.05, 0.68, 0.049]} rotation={[-0.124, -0.04, -0.004]}>
//         <mesh geometry={nodes.Object_13.geometry} material={materials.JAVASCRIPT} />
//         <mesh geometry={nodes.Object_13_1.geometry} material={materials.BORDAS_CROMADO} />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/javascript-transformed.glb')
