/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 react-logo-v1.glb -t -T 
Files: react-logo-v1.glb [1.49MB] > react-logo-v1-transformed.glb [60.7KB] (96%)
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    ['react-logo']: THREE.Mesh
  }
  materials: {
    skin: THREE.MeshStandardMaterial
  }
}

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements['mesh']>>

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/react-logo-v1-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['react-logo'].geometry} material={materials.skin} />
    </group>
  )
}

useGLTF.preload('/react-logo-v1-transformed.glb')
